'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {ArrowLeft,BookOpenCheck,CheckCircle2,RefreshCcw,Search,TriangleAlert,UserRoundCog} from 'lucide-react';
import Shell from '@/components/Shell';
import {api} from '@/lib/api';
import {digitsOnlyInput,toUpperInput} from '@/lib/formRules';

const GARMENTS=['','10','11','12','13','14','15','16','S','M','L','XL','2XL','3XL'];
function pretty(v?:string){return v?v.replaceAll('_',' '):'—'}
function idLabel(x:any){return x?.identityNumber?`${x.nationality==='VENEZOLANO'?'V':'E'}-${x.identityNumber}`:'SIN CÉDULA'}
function originLabel(v:string){return v==='PLAN_ACTUAL'?'PLAN DEL NUEVO GRADO':v==='MATERIA_PENDIENTE'?'MATERIA PENDIENTE':'REPITENCIA'}
function heightParts(cm?:number){return {m:cm?Math.floor(cm/100):1,c:cm?cm%100:50}}
function weightParts(g?:number){return {kg:g?Math.floor(g/1000):'',gr:g?g%1000:0}}

export default function ReEnrollmentPage(){
  const router=useRouter();
  const [years,setYears]=useState<any[]>([]),[targetYearId,setTargetYearId]=useState(''),[nationality,setNationality]=useState('VENEZOLANO'),[identity,setIdentity]=useState(''),[data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[reinstating,setReinstating]=useState(false),[err,setErr]=useState(''),[success,setSuccess]=useState(''),[sectionId,setSectionId]=useState('');
  const [address,setAddress]=useState(''),[phone,setPhone]=useState(''),[email,setEmail]=useState('');
  useEffect(()=>{api('/academic/years').then((y:any[])=>{setYears(y);const active=y.find(x=>x.active)||y[0];if(active)setTargetYearId(active.id)}).catch((e:any)=>setErr(e.message))},[]);
  async function lookup(e?:FormEvent,preserveSuccess=false){e?.preventDefault();if(!targetYearId||!identity)return;if(!preserveSuccess)setSuccess('');setLoading(true);setErr('');try{const p=new URLSearchParams({nationality,identityNumber:identity,targetAcademicYearId:targetYearId});const r=await api(`/enrollments/re-enrollment/lookup?${p}`);setData(r);setSectionId(r.recommendation?.suggestedSection?.id||'');setAddress(r.student.address||'');setPhone(r.student.phone||'');setEmail(r.student.email||'')}catch(e:any){setData(null);setErr(e.message)}finally{setLoading(false)}}
  const primary=data?.student?.representatives?.find((x:any)=>x.isPrimary)||data?.student?.representatives?.[0];
  const latestAnthro=data?.student?.anthropometrics?.[0];
  const hp=useMemo(()=>heightParts(latestAnthro?.heightCm),[latestAnthro?.heightCm]);
  const wp=useMemo(()=>weightParts(latestAnthro?.weightGrams),[latestAnthro?.weightGrams]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!data?.recommendation)return;const f=new FormData(e.currentTarget);setSaving(true);setErr('');try{const meters=Number(f.get('meters')||0),centimeters=Number(f.get('centimeters')||0),kg=Number(f.get('kg')||0),grams=Number(f.get('grams')||0);const body:any={studentId:data.student.id,targetAcademicYearId:targetYearId,sectionId,registrationDate:f.get('registrationDate'),address,phone:phone||undefined,email:email||undefined};if(meters||centimeters||kg||grams){body.heightCm=meters*100+centimeters;body.weightGrams=kg*1000+grams;body.shirtSize=f.get('shirtSize')||undefined;body.pantSize=f.get('pantSize')||undefined;body.shoeSize=f.get('shoeSize')?Number(f.get('shoeSize')):undefined}const created=await api('/enrollments/re-enrollment',{method:'POST',body:JSON.stringify(body)});router.push(`/enrollments/${created.id}`)}catch(e:any){setErr(e.message)}finally{setSaving(false)}}
  async function reinstate(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!data?.reinstatement?.enrollmentId)return;const f=new FormData(e.currentTarget);const returnDate=String(f.get('returnDate')||'');setReinstating(true);setErr('');setSuccess('');try{const body:any={returnDate,address,phone:phone||undefined,email:email||undefined};const updated=await api(`/enrollments/${data.reinstatement.enrollmentId}/reinstate`,{method:'POST',body:JSON.stringify(body)});setSuccess(`REINCORPORACIÓN COMPLETADA. El estudiante vuelve a estar activo con condición ${pretty(updated.condition)}${updated.listNumber?` y N° de lista ${updated.listNumber}`:'; la nómina provisional se ordenará por cédula'}.`);await lookup(undefined,true)}catch(e:any){setErr(e.message)}finally{setReinstating(false)}}
  return <Shell title="Reinscripción">
    <div className="page-heading"><div><span className="eyebrow">Continuidad académica</span><h1>Reinscribir estudiante</h1><p>Busque por cédula. El sistema recupera la ficha y el representante, lee la definitiva del año anterior y propone automáticamente grado, condición y materias.</p></div><Link className="btn secondary" href="/enrollments"><ArrowLeft size={17}/> Volver</Link></div>
    {success&&<div className="success-banner"><strong>{success}</strong></div>}{err&&<div className="alert">{err}</div>}
    <form className="card form-section enrollment-lookup" onSubmit={lookup}><div className="section-head"><div><h2>1. Identificar estudiante</h2><p>La nacionalidad y la cédula son campos separados.</p></div><span className="step-pill">1</span></div><div className="form-grid reenroll-search-grid"><div><label>Año escolar destino *</label><select className="input" value={targetYearId} onChange={e=>{setTargetYearId(e.target.value);setData(null)}} required><option value="">Seleccione</option>{years.map(y=><option key={y.id} value={y.id}>{y.name}{y.active?' · ACTIVO':''}</option>)}</select></div><div><label>Nacionalidad *</label><select className="input" value={nationality} onChange={e=>setNationality(e.target.value)}><option value="VENEZOLANO">V</option><option value="EXTRANJERO">E</option></select></div><div><label>Cédula *</label><input className="input" value={identity} onChange={e=>setIdentity(e.target.value.replace(/\D/g,''))} onInput={digitsOnlyInput} inputMode="numeric" required/></div><button className="btn lookup-btn" disabled={loading||!targetYearId||!identity}><Search size={17}/>{loading?'Buscando…':'Buscar expediente'}</button></div></form>
    {data&&<div className="stack">
      <section className="card form-section"><div className="section-head"><div><h2>2. Expediente recuperado</h2><p>Los datos personales pueden actualizarse antes de formalizar la nueva matrícula.</p></div><span className="step-pill">2</span></div><div className="student-reenroll-head"><div className="avatar-lg">{data.student.firstName?.[0]}{data.student.lastName?.[0]}</div><div><h3>{[data.student.firstName,data.student.middleName,data.student.lastName,data.student.secondLastName].filter(Boolean).join(' ')}</h3><p>{idLabel(data.student)} · {data.student.sex} · Nacimiento {new Date(data.student.birthDate).toLocaleDateString('es-VE')}</p></div><Link className="btn secondary" href={`/students/${data.student.id}/edit`}>Editar ficha completa</Link></div><div className="form-grid cols-3 quick-update-grid"><div className="span-2"><label>Dirección actual</label><input className="input uppercase" value={address} onChange={e=>setAddress(e.target.value.toLocaleUpperCase('es-VE'))} onInput={toUpperInput}/></div><div><label>Teléfono</label><input className="input" value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,''))} onInput={digitsOnlyInput} inputMode="numeric"/></div><div><label>Correo</label><input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value.toLowerCase())}/></div><div><label>Última sección</label><div className="input read-only">{data.previousEnrollment?`${data.previousEnrollment.gradeLevel}° · ${data.previousEnrollment.section.name}`:data.reinstatement?`${data.reinstatement.gradeLevel}° · ${data.reinstatement.section?.name}`:'—'}</div></div><div><label>Última mención</label><div className="input read-only">{data.previousEnrollment?.section?.mentionName||data.reinstatement?.section?.mentionName||'SIN DEFINIR'}</div></div><div><label>Último plan</label><div className="input read-only">{data.previousEnrollment?`${data.previousEnrollment.studyPlan.code} · ${data.previousEnrollment.studyPlan.name}`:data.reinstatement?`${data.reinstatement.studyPlan?.code} · ${data.reinstatement.studyPlan?.name}`:'—'}</div></div></div>
        <div className="representative-summary"><div><h3>Representante vinculado</h3>{primary?<><strong>{primary.representative.firstName} {primary.representative.lastName}</strong><p>{idLabel(primary.representative)} · {pretty(primary.relationship)} · {primary.representative.phone1}</p></>:<p className="warning-text">El estudiante no tiene representante vinculado.</p>}</div>{primary?<Link className="btn secondary" href={`/representatives/${primary.representativeId}/edit`}><UserRoundCog size={16}/> Actualizar representante</Link>:<div className="row-actions"><Link className="btn secondary" href={`/students/${data.student.id}/representatives/link`}>Asignar existente</Link><Link className="btn" href={`/representatives/new?studentId=${data.student.id}`}>Crear representante</Link></div>}</div>
      </section>
      {data.alreadyEnrollmentActive&&<div className="alert"><strong>Este estudiante ya está matriculado en {data.targetAcademicYear.name} con condición {pretty(data.alreadyEnrolled?.condition)}.</strong> Revise la matrícula existente antes de intentar una reinscripción.</div>}
      {data.alreadyEnrolled&&!data.alreadyEnrollmentActive&&!data.reinstatement&&<div className="warning-banner"><div><strong>Ya existe una matrícula en {data.targetAcademicYear.name} con condición {pretty(data.alreadyEnrolled.condition)}.</strong><span>No se creará una segunda matrícula para el mismo estudiante y año escolar. Revise el histórico antes de continuar.</span></div><Link className="btn secondary" href={`/enrollments/${data.alreadyEnrolled.id}`}>Ver matrícula</Link></div>}
      {data.reinstatement&&<form className="card form-section" onSubmit={reinstate}><div className="section-head"><div><h2>3. Reincorporación al mismo año escolar</h2><p>El estudiante está retirado, pero puede regresar a la institución sin crear una matrícula duplicada.</p></div><span className="step-pill">3</span></div><div className="warning-banner"><div><strong>Matrícula retirada en {data.targetAcademicYear.name}</strong><span>Condición actual: {pretty(data.reinstatement.currentCondition)} · Se restaurará como {pretty(data.reinstatement.restoreCondition)} · Sección {data.reinstatement.gradeLevel}° {data.reinstatement.section?.name}.{data.reinstatement.withdrawal?.withdrawalDate?` Retiro: ${new Date(data.reinstatement.withdrawal.withdrawalDate).toLocaleDateString('es-VE')}.`:''}</span></div><RefreshCcw size={22}/></div><div className="form-grid cols-3"><div><label>Fecha de reincorporación *</label><input className="input" type="date" name="returnDate" min={data.reinstatement.withdrawal?.withdrawalDate?String(data.reinstatement.withdrawal.withdrawalDate).slice(0,10):undefined} max={data.targetAcademicYear?.endDate?String(data.targetAcademicYear.endDate).slice(0,10):undefined} defaultValue={(()=>{const today=new Date().toISOString().slice(0,10);const withdrawal=data.reinstatement.withdrawal?.withdrawalDate?String(data.reinstatement.withdrawal.withdrawalDate).slice(0,10):today;return today>withdrawal?today:withdrawal})()} required/><span className="field-help">No puede ser anterior a la fecha de retiro.</span></div><div><label>Número de lista actual</label><div className="input read-only">{data.reinstatement.listNumber||'FUERA DE NÓMINA'}</div></div><div><label>Regla de nómina</label><div className="input read-only">SI REGRESA DESPUÉS DEL CIERRE Y ESTABA FUERA DE NÓMINA, IRÁ AL FINAL</div></div></div><p className="info-note">Al pulsar <strong>Reincorporar estudiante</strong>, esta misma matrícula dejará de estar RETIRADA y recuperará su condición académica anterior. No se crea una matrícula nueva. Después de completar la operación, esta pantalla mostrará la confirmación de reincorporación.</p><p className="info-note">Si el retiro fue antes del 1° de noviembre y la reincorporación también ocurre antes del cierre, volverá a la nómina provisional y se ordenará por cédula. Si regresa después de fijada la nómina y estaba fuera de ella, recibirá el siguiente número al final. Si se retiró después del cierre, conserva su número.</p><div className="action-bar"><Link className="btn secondary" href={`/enrollments/${data.reinstatement.enrollmentId}`}>Ver matrícula retirada</Link><button className="btn" disabled={reinstating||!primary}><RefreshCcw size={17}/>{reinstating?'Reincorporando…':'Reincorporar estudiante'}</button></div></form>}
      {!data.previousEnrollment&&!data.reinstatement&&<div className="warning-banner"><div><strong>No existe matrícula anterior utilizable.</strong><span>Este caso corresponde a una primera matrícula o requiere revisar el histórico.</span></div><Link className="btn secondary" href="/enrollments/new">Ir a primera matrícula</Link></div>}
      {data.previousEnrollment&&!data.reinstatement&&<section className="card form-section"><div className="section-head"><div><h2>3. Definitiva del año anterior</h2><p>Esta información es de solo lectura y proviene de Notas.</p></div><span className="step-pill">3</span></div><div className="outcome-header"><div><span className="muted">Año cursado</span><strong>{data.previousEnrollment.academicYear.name}</strong></div><div><span className="muted">Grado / sección</span><strong>{data.previousEnrollment.gradeLevel}° · {data.previousEnrollment.section.name}</strong></div><div><span className="muted">Mención</span><strong>{data.previousEnrollment.section.mentionName||'SIN DEFINIR'}</strong></div><div><span className="muted">Resultados cerrados</span><strong>{data.academicOutcome?.resultCount||0} / {data.academicOutcome?.expectedCount||0}</strong></div></div>{!data.academicOutcome?.complete?<div className="warning-banner"><div><strong>Cierre académico incompleto</strong><span>{(data.academicOutcome?.missingSubjects||[]).length>0?`Faltan definitivas: ${(data.academicOutcome.missingSubjects||[]).map((x:any)=>x.name).join(', ')}. `:''}{(data.academicOutcome?.unresolvedPendingSubjects||[]).length>0?`Materias pendientes aún sin resolver: ${(data.academicOutcome.unresolvedPendingSubjects||[]).map((x:any)=>x.name).join(', ')}.`:''}</span></div><TriangleAlert size={22}/></div>:<><div className="decision-card"><div><span>Condición resultante</span><strong>{pretty(data.recommendation.condition)}</strong></div><div><span>Grado propuesto</span><strong>{data.recommendation.targetGradeLevel?`${data.recommendation.targetGradeLevel}° AÑO`:'GRADUACIÓN'}</strong></div><div><span>Materias reprobadas</span><strong>{data.academicOutcome.failedSubjects.length}</strong></div></div>{data.academicOutcome.failedSubjects.length>0&&<div className="table-wrap"><table><thead><tr><th>Materia reprobada</th><th>Nota</th><th>Procedencia</th></tr></thead><tbody>{data.academicOutcome.failedSubjects.map((x:any)=><tr key={x.studyPlanSubjectId}><td>{x.name}</td><td>{x.numericScore??x.letterScore??'—'}</td><td>{data.previousEnrollment.gradeLevel}° · {data.previousEnrollment.academicYear.name}</td></tr>)}</tbody></table></div>}</>}
      </section>}
      {!data.reinstatement&&data.recommendation?.graduationEligible&&<div className="success-banner graduation-banner"><CheckCircle2 size={20}/><div><strong>Elegible para graduación.</strong><span>El estudiante aprobó todas las materias del último grado del plan. No corresponde reinscripción al siguiente grado.</span></div></div>}
      {!data.reinstatement&&data.recommendation&&!data.recommendation.graduationEligible&&data.academicOutcome?.complete&&!data.alreadyEnrolled&&<form className="stack" onSubmit={submit}>
        <section className="card form-section"><div className="section-head"><div><h2>4. Propuesta de reinscripción</h2><p>La condición, grado y materias no son editables por Secretaría; los determina la definitiva.</p></div><span className="step-pill">4</span></div><div className="decision-grid"><div><label>Año escolar</label><div className="input read-only">{data.targetAcademicYear.name}</div></div><div><label>Plan</label><div className="input read-only">{data.recommendation.studyPlan.code} · {data.recommendation.studyPlan.name}</div></div><div><label>Condición</label><div className="input read-only">{pretty(data.recommendation.condition)}</div></div><div><label>Mención</label><div className="input read-only">{data.recommendation.mentionName||'SIN DEFINIR'}</div></div><div><label>Grado</label><div className="input read-only">{data.recommendation.targetGradeLevel}° AÑO</div></div><div><label>Sección *</label><select className="input" value={sectionId} onChange={e=>setSectionId(e.target.value)} required><option value="">Seleccione</option>{data.recommendation.sections.map((s:any)=><option key={s.id} value={s.id}>{s.name}{s.shift?` · ${s.shift}`:''}{s.id===data.recommendation.suggestedSection?.id?' · SUGERIDA':''}</option>)}</select></div><div><label>Fecha de inscripción *</label><input className="input" type="date" name="registrationDate" defaultValue={new Date().toISOString().slice(0,10)} required/></div></div>
          {data.recommendation.sections.length===0&&<div className="warning-banner"><div><strong>No existen secciones configuradas para el grado propuesto.</strong><span>Cree la sección correspondiente en Configuración anual.</span></div><Link className="btn secondary" href="/enrollments/configuration">Configurar secciones</Link></div>}
          <div className="section-title"><div><h3>Materias a cursar</h3><p className="muted">REGULAR: plan completo del nuevo grado · MATERIA PENDIENTE: nuevo grado + pendientes (en el último grado, solo pendientes) · REPITIENTE: únicamente reprobadas.</p></div></div><div className="curriculum-grid">{data.recommendation.subjects.map((s:any)=><div className={`curriculum-card origin-${s.origin.toLowerCase()}`} key={`${s.studyPlanSubjectId}-${s.origin}`}><BookOpenCheck size={18}/><div><strong>{s.name}</strong><span>{originLabel(s.origin)} · {s.gradeLevel}°</span></div></div>)}</div>
        </section>
        <section className="card form-section"><div className="section-head"><div><h2>5. Actualización antropométrica</h2><p>La nueva medición queda ligada a esta matrícula y conserva el histórico anterior.</p></div><span className="step-pill">5</span></div>{latestAnthro&&<p className="info-note">Última medición: {Math.floor(latestAnthro.heightCm/100)} m {latestAnthro.heightCm%100} cm · {Math.floor(latestAnthro.weightGrams/1000)} kg {latestAnthro.weightGrams%1000} g · {new Date(latestAnthro.measuredAt).toLocaleDateString('es-VE')}</p>}<div className="form-grid cols-3"><div className="inline-fields"><div><label>Estatura · metros</label><input className="input" type="number" name="meters" min="0" max="2" defaultValue={hp.m} required/></div><div><label>centímetros</label><input className="input" type="number" name="centimeters" min="0" max="99" defaultValue={hp.c} required/></div></div><div className="inline-fields"><div><label>Peso · kg</label><input className="input" type="number" name="kg" min="10" max="300" defaultValue={wp.kg} required/></div><div><label>gramos</label><input className="input" type="number" name="grams" min="0" max="999" defaultValue={wp.gr} required/></div></div><div><label>Talla zapatos</label><input className="input" name="shoeSize" type="number" min="20" max="46" defaultValue={latestAnthro?.shoeSize||''}/></div><div><label>Talla camisa</label><select className="input" name="shirtSize" defaultValue={latestAnthro?.shirtSize||''}>{GARMENTS.map(x=><option key={x||'none'} value={x}>{x||'Seleccione'}</option>)}</select></div><div><label>Talla pantalón</label><select className="input" name="pantSize" defaultValue={latestAnthro?.pantSize||''}>{GARMENTS.map(x=><option key={x||'none'} value={x}>{x||'Seleccione'}</option>)}</select></div></div></section>
        <div className="action-bar"><Link className="btn secondary" href="/enrollments">Cancelar</Link><button className="btn" disabled={saving||!sectionId||!primary}><RefreshCcw size={17}/>{saving?'Procesando…':'Formalizar reinscripción'}</button></div>
      </form>}
    </div>}
  </Shell>
}
