'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import {useParams} from 'next/navigation';
import Link from 'next/link';
import {BookOpenCheck,ClipboardCopy,Edit3,FileText,GraduationCap,HeartPulse,Link2,Plus,Power,Trash2,UsersRound} from 'lucide-react';
import Shell from '@/components/Shell';
import {API,api,token} from '@/lib/api';
import {DIGITS_PATTERN,NAME_PATTERN,digitsOnlyInput,nameOnlyInput,toUpperInput} from '@/lib/formRules';
import {calculateAge} from '@/lib/age';

const typeLabel=(v?:string)=>v==='COCINERO'?'COCINERA(O)':v?v.replaceAll('_',' '):'—';
const qualLabel:Record<string,string>={PREGRADO:'PREGRADO',ESPECIALIZACION:'ESPECIALIZACIÓN',MAESTRIA:'MAESTRÍA',DOCTORADO:'DOCTORADO',OTRO:'OTRO'};
const CONDITION_LABELS:Record<string,string>={ACTIVO:'ACTIVO',REPOSO_CONTINUO:'REPOSO CONTINUO',INCAPACITADO:'INCAPACITADO',JUBILADO:'JUBILADO',EN_PROCESO_JUBILACION:'EN PROCESO DE JUBILACIÓN',PROCESO_ADMINISTRATIVO:'PROCESO ADMINISTRATIVO'};
const EDUCATION_LEVELS:[string,string][]=[
  ['NO_ESTUDIA','NO ESTUDIA'],['EDUCACION_INICIAL','EDUCACIÓN INICIAL'],
  ['1_GRADO','1° GRADO'],['2_GRADO','2° GRADO'],['3_GRADO','3° GRADO'],['4_GRADO','4° GRADO'],['5_GRADO','5° GRADO'],['6_GRADO','6° GRADO'],
  ['1_ANO_MEDIA_GENERAL','1° AÑO · MEDIA GENERAL'],['2_ANO_MEDIA_GENERAL','2° AÑO · MEDIA GENERAL'],['3_ANO_MEDIA_GENERAL','3° AÑO · MEDIA GENERAL'],['4_ANO_MEDIA_GENERAL','4° AÑO · MEDIA GENERAL'],['5_ANO_MEDIA_GENERAL','5° AÑO · MEDIA GENERAL'],
  ['1_ANO_MEDIA_TECNICA','1° AÑO · MEDIA TÉCNICA'],['2_ANO_MEDIA_TECNICA','2° AÑO · MEDIA TÉCNICA'],['3_ANO_MEDIA_TECNICA','3° AÑO · MEDIA TÉCNICA'],['4_ANO_MEDIA_TECNICA','4° AÑO · MEDIA TÉCNICA'],['5_ANO_MEDIA_TECNICA','5° AÑO · MEDIA TÉCNICA'],['6_ANO_MEDIA_TECNICA','6° AÑO · MEDIA TÉCNICA'],
  ['TSU','TÉCNICO SUPERIOR UNIVERSITARIO'],['UNIVERSITARIO_PREGRADO','UNIVERSITARIO · PREGRADO'],['ESPECIALIZACION','ESPECIALIZACIÓN'],['MAESTRIA','MAESTRÍA'],['DOCTORADO','DOCTORADO'],['OTRO','OTRO'],
];
const levelLabel=(v?:string)=>EDUCATION_LEVELS.find(([x])=>x===v)?.[1]||typeLabel(v);
function identity(s:any){return `${s.nationality==='VENEZOLANO'?'V':'E'}-${s.identityNumber}`}
function childAge(c:any){return c?.birthDate?calculateAge(String(c.birthDate).slice(0,10)):null}
function serviceYears(value?:string){if(!value)return null;const start=new Date(value);if(Number.isNaN(start.getTime()))return null;const now=new Date();let years=now.getFullYear()-start.getFullYear();const anniversary=new Date(now.getFullYear(),start.getMonth(),start.getDate());if(now<anniversary)years--;return Math.max(0,years)}

export default function StaffDetail(){
  const {id}=useParams<{id:string}>(); const [row,setRow]=useState<any>(); const [years,setYears]=useState<any[]>([]); const [yearId,setYearId]=useState(''); const [sections,setSections]=useState<any[]>([]); const [sectionId,setSectionId]=useState(''); const [subjects,setSubjects]=useState<any[]>([]); const [subjectId,setSubjectId]=useState(''); const [msg,setMsg]=useState(''); const [err,setErr]=useState(''); const [editingQ,setEditingQ]=useState<any>(null);
  const [editingChild,setEditingChild]=useState<any>(null); const [childStudying,setChildStudying]=useState(false); const [childDisease,setChildDisease]=useState(false);
  async function load(){try{const [s,y]=await Promise.all([api(`/staff/${id}`),api('/academic/years')]);setRow(s);setYears(y);const active=y.find((x:any)=>x.active)||y[0];if(!yearId&&active)setYearId(active.id);setErr('')}catch(e:any){setErr(e.message)}}
  useEffect(()=>{load()},[id]);
  useEffect(()=>{if(!yearId){setSections([]);return}api(`/academic/sections?academicYearId=${yearId}`).then((x:any[])=>{setSections(x);if(sectionId&&!x.some(s=>s.id===sectionId)){setSectionId('');setSubjects([]);setSubjectId('')}}).catch(e=>setErr(e.message))},[yearId]);
  useEffect(()=>{const sec=sections.find(s=>s.id===sectionId);if(!sec){setSubjects([]);setSubjectId('');return}api(`/academic/plans/${sec.studyPlanId}/curriculum`).then((p:any)=>{const list=(p.subjects||[]).filter((x:any)=>x.gradeLevel===sec.gradeLevel&&x.active);setSubjects(list);setSubjectId(list[0]?.id||'')}).catch(e=>setErr(e.message))},[sectionId,sections]);
  async function act(path:string,options:RequestInit,text:string){try{await api(path,options);await load();setMsg(text);setErr('')}catch(e:any){setErr(e.message)}}
  async function qualification(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const body={type:f.get('type'),title:f.get('title'),institution:f.get('institution')||undefined,year:f.get('year')?Number(f.get('year')):undefined};try{await api(editingQ?`/staff/${id}/qualifications/${editingQ.id}`:`/staff/${id}/qualifications`,{method:editingQ?'PATCH':'POST',body:JSON.stringify(body)});const wasEditing=!!editingQ;setEditingQ(null);form.reset();await load();setMsg(wasEditing?'Título actualizado':'Título agregado');setErr('')}catch(x:any){setErr(x.message)}}
  async function childSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const body:any={firstName:f.get('firstName'),middleName:f.get('middleName')||undefined,lastName:f.get('lastName'),secondLastName:f.get('secondLastName')||undefined,identityNumber:f.get('identityNumber')||undefined,birthDate:f.get('birthDate'),studying:childStudying,educationLevel:childStudying?f.get('educationLevel'):undefined,institutionName:childStudying?f.get('institutionName')||undefined:undefined,hasDisease:childDisease,diseaseDescription:childDisease?f.get('diseaseDescription')||undefined:undefined};try{const editing=editingChild;await api(editing?`/staff/${id}/children/${editing.id}`:`/staff/${id}/children`,{method:editing?'PATCH':'POST',body:JSON.stringify(body)});setEditingChild(null);setChildStudying(false);setChildDisease(false);form.reset();await load();setMsg(editing?'Datos del hijo actualizados':'Hijo registrado');setErr('')}catch(x:any){setErr(x.message)}}
  function editChild(c:any){setEditingChild(c);setChildStudying(!!c.studying);setChildDisease(!!c.hasDisease);setTimeout(()=>document.getElementById('child-form')?.scrollIntoView({behavior:'smooth',block:'start'}),40)}
  async function assign(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!sectionId||!subjectId){setErr('Seleccione sección y materia');return}await act(`/staff/${id}/assignments`,{method:'POST',body:JSON.stringify({sectionId,studyPlanSubjectId:subjectId})},'Asignación docente registrada')}
  async function openCertificate(){try{const t=token();const r=await fetch(`${API}/reports/work-certificate/${id}.pdf`,{headers:t?{Authorization:`Bearer ${t}`}:{}});if(!r.ok)throw new Error('No fue posible generar la constancia');const blob=await r.blob();const url=URL.createObjectURL(blob);window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e:any){setErr(e.message)}}
  async function copyText(text?:string){if(!text)return;try{await navigator.clipboard.writeText(text);setMsg('Descripción copiada')}catch{setErr('No fue posible copiar el texto')}}
  const age=useMemo(()=>row?.birthDate?calculateAge(String(row.birthDate).slice(0,10)):null,[row]);
  const childMetrics=useMemo(()=>{const children=row?.children||[];let upTo21=0,over21=0;for(const c of children){const a=childAge(c);if(a===null)continue;if(a<=21)upTo21++;else over21++}return {total:children.length,upTo21,over21}},[row]);
  if(!row)return <Shell title="Personal">{err&&<div className="alert">{err}</div>}<div className="card">Cargando…</div></Shell>;
  return <Shell title={`${row.firstName} ${row.lastName}`}>{msg&&<div className="success-banner">{msg}</div>}{err&&<div className="alert">{err}</div>}
    <div className="profile-head card"><div className="avatar-lg">{row.firstName?.[0]}{row.lastName?.[0]}</div><div className="profile-main"><div className="profile-title"><h1>{[row.firstName,row.middleName,row.lastName,row.secondLastName].filter(Boolean).join(' ')}</h1><span className={`status ${row.active?'ok':'neutral'}`}>{row.active?'ACTIVO':'INACTIVO'}</span><span className="status neutral">{typeLabel(row.staffType)}</span><span className={`status ${row.employmentCondition==='ACTIVO'?'ok':'neutral'}`}>{CONDITION_LABELS[row.employmentCondition]||row.employmentCondition||'ACTIVO'}</span></div><p>{identity(row)} · {row.sex?typeLabel(row.sex):'SEXO NO INDICADO'}{age!==null?` · ${age} AÑOS`:''}</p><div className="profile-meta"><span>{row.phone||'Sin teléfono'}</span><span>{row.email||'Sin correo'}</span><span>{row.cargoDescription||row.institutionalFunction||'Cargo no indicado'}</span></div></div><div className="profile-actions"><Link className="btn secondary" href={`/staff/${id}/edit`}><Edit3 size={16}/> Editar</Link><button className="btn secondary" onClick={openCertificate}><FileText size={16}/> Constancia</button><button className="btn secondary" onClick={()=>act(`/staff/${id}/active`,{method:'PATCH',body:JSON.stringify({active:!row.active})},row.active?'Personal inactivado':'Personal reactivado')}><Power size={16}/> {row.active?'Inactivar':'Reactivar'}</button></div></div>

    <div className="details-grid"><section className="card"><h3>Datos personales y laborales</h3><dl className="details-list"><div><dt>Tipo</dt><dd>{typeLabel(row.staffType)}</dd></div><div><dt>Estado civil</dt><dd>{typeLabel(row.maritalStatus)}</dd></div><div><dt>Tipo de sangre</dt><dd>{row.bloodType||'—'}</dd></div><div><dt>Dirección</dt><dd>{row.address||'—'}</dd></div><div><dt>Nacimiento</dt><dd>{row.birthDate?new Date(row.birthDate).toLocaleDateString('es-VE'):'—'} · {row.birthPlace||'—'}</dd></div><div><dt>Código de cargo</dt><dd>{row.cargoCode||'—'}</dd></div><div><dt>Cargo</dt><dd>{row.cargoDescription||'—'}</dd></div><div className="wide"><dt>Función institucional</dt><dd>{row.institutionalFunction||'—'}</dd></div><div><dt>Ingreso MPPE</dt><dd>{row.ministryEntryDate?new Date(row.ministryEntryDate).toLocaleDateString('es-VE'):'—'}</dd></div><div><dt>Años de servicio</dt><dd>{serviceYears(row.ministryEntryDate)===null?'—':`${serviceYears(row.ministryEntryDate)} años`}</dd></div><div><dt>Condición laboral</dt><dd>{CONDITION_LABELS[row.employmentCondition]||row.employmentCondition||'ACTIVO'}</dd></div><div><dt>Hijos registrados</dt><dd>{childMetrics.total}</dd></div><div><dt>Discapacidad</dt><dd>{row.disability?'SÍ':'NO'} · Informe médico: {row.medicalReport?'SÍ':'NO'}</dd></div>
      {row.employmentCondition==='REPOSO_CONTINUO'&&<><div className="wide"><dt>Enfermedad / reposo continuo</dt><dd>{row.continuousLeaveDisease||'—'}</dd></div><div><dt>Cantidad de reposos</dt><dd>{row.continuousLeaveCount||'—'}</dd></div></>}
      {row.employmentCondition==='INCAPACITADO'&&<><div><dt>Ente ejecutor</dt><dd>{row.incapacityExecutor||'—'}</dd></div><div><dt>Fecha de incapacidad</dt><dd>{row.incapacityDate?new Date(row.incapacityDate).toLocaleDateString('es-VE'):'—'}</dd></div></>}
      {row.employmentCondition==='JUBILADO'&&<div><dt>Fecha de jubilación</dt><dd>{row.retirementDate?new Date(row.retirementDate).toLocaleDateString('es-VE'):'—'}</dd></div>}
      {row.employmentCondition==='EN_PROCESO_JUBILACION'&&<><div><dt>Fecha introducción jubilación</dt><dd>{row.retirementProcessDate?new Date(row.retirementProcessDate).toLocaleDateString('es-VE'):'—'}</dd></div><div className="wide"><dt>Observación</dt><dd>{row.retirementProcessObservation||'—'}</dd></div></>}
      {row.employmentCondition==='PROCESO_ADMINISTRATIVO'&&<><div><dt>Fecha del proceso</dt><dd>{row.administrativeProcessDate?new Date(row.administrativeProcessDate).toLocaleDateString('es-VE'):'—'}</dd></div><div className="wide"><dt>Observación</dt><dd>{row.administrativeProcessObservation||'—'}</dd></div></>}
      </dl></section>
      <section className="card"><div className="section-head"><div><h3>Vivienda y salud</h3></div><HeartPulse/></div><dl className="details-list"><div><dt>Vivienda</dt><dd>{typeLabel(row.housingTenure)}</dd></div><div><dt>¿Necesita arreglo?</dt><dd>{row.housingTenure==='PROPIA'?(row.housingRepairNeeded?'SÍ':'NO'):'NO APLICA'}</dd></div>{row.housingRepairNeeded&&<div className="wide"><dt>Arreglo requerido</dt><dd>{row.housingRepairDescription||'—'} <button className="btn secondary mini-btn" type="button" onClick={()=>copyText(row.housingRepairDescription)}><ClipboardCopy size={13}/> Copiar</button></dd></div>}<div><dt>Enfermedad</dt><dd>{row.hasDisease?'SÍ':'NO'}</dd></div>{row.hasDisease&&<div className="wide"><dt>Descripción</dt><dd>{row.diseaseDescription||'—'}</dd></div>}<div><dt>Amerita operación</dt><dd>{row.needsSurgery?'SÍ':'NO'}</dd></div>{row.needsSurgery&&<div className="wide"><dt>Operación</dt><dd>{row.surgeryDescription||'—'}</dd></div>}<div><dt>Usa lentes</dt><dd>{row.wearsGlasses?'SÍ':'NO'}</dd></div>{row.wearsGlasses&&<div className="wide"><dt>Condición visual</dt><dd>{row.eyeConditionDescription||'—'}</dd></div>}</dl></section>
      <section className="card"><h3>Tallas y datos bancarios</h3><dl className="details-list"><div><dt>Pantalón</dt><dd>{row.pantSize||'—'}</dd></div><div><dt>Camisa</dt><dd>{row.shirtSize||'—'}</dd></div><div><dt>Zapatos</dt><dd>{row.shoeSize||'—'}</dd></div><div><dt>Banco</dt><dd>{row.bankName||'—'}</dd></div><div><dt>Tipo de cuenta</dt><dd>{typeLabel(row.accountType)}</dd></div><div className="wide"><dt>Número de cuenta</dt><dd>{row.accountNumber||'—'}</dd></div></dl>{row.user&&<div className="info-banner">Acceso al sistema: {row.user.email} · {typeLabel(row.user.role)} · {row.user.active?'ACTIVO':'INACTIVO'}</div>}</section>
    </div>

    <div className="section-title"><div><h2>Hijos y carga familiar</h2><p className="muted">Registro individual para calcular automáticamente hijos menores o iguales a 21 años y mayores de 21 años.</p></div></div>
    <div className="grid compact-grid metrics-3"><div className="card metric-card"><UsersRound/><div><span className="muted">Total de hijos</span><strong>{childMetrics.total}</strong></div></div><div className="card metric-card"><UsersRound/><div><span className="muted">≤ 21 años</span><strong>{childMetrics.upTo21}</strong></div></div><div className="card metric-card"><UsersRound/><div><span className="muted">&gt; 21 años</span><strong>{childMetrics.over21}</strong></div></div></div>
    <div className="details-grid"><form id="child-form" key={editingChild?.id||'new-child'} className="card form-section" onSubmit={childSubmit}><div className="section-head"><div><h3>{editingChild?'Editar hijo':'Registrar hijo'}</h3><p>La fecha de nacimiento determina automáticamente el grupo de edad.</p></div><UsersRound/></div><div className="form-grid cols-2">
      <div><label>Primer nombre *</label><input className="input uppercase" name="firstName" defaultValue={editingChild?.firstName||''} required pattern={NAME_PATTERN} onInput={nameOnlyInput}/></div><div><label>Segundo nombre</label><input className="input uppercase" name="middleName" defaultValue={editingChild?.middleName||''} pattern={NAME_PATTERN} onInput={nameOnlyInput}/></div><div><label>Primer apellido *</label><input className="input uppercase" name="lastName" defaultValue={editingChild?.lastName||''} required pattern={NAME_PATTERN} onInput={nameOnlyInput}/></div><div><label>Segundo apellido</label><input className="input uppercase" name="secondLastName" defaultValue={editingChild?.secondLastName||''} pattern={NAME_PATTERN} onInput={nameOnlyInput}/></div><div><label>Cédula (si posee)</label><input className="input" name="identityNumber" defaultValue={editingChild?.identityNumber||''} pattern={DIGITS_PATTERN} onInput={digitsOnlyInput} inputMode="numeric"/></div><div><label>Fecha de nacimiento *</label><input className="input" type="date" name="birthDate" defaultValue={editingChild?.birthDate?String(editingChild.birthDate).slice(0,10):''} required/></div>
      <label className="check-card"><input type="checkbox" checked={childStudying} onChange={e=>setChildStudying(e.target.checked)}/><span><strong>¿Está estudiando?</strong><small>Habilita nivel e institución educativa.</small></span></label>
      {childStudying&&<><div><label>Nivel educativo *</label><select className="input" name="educationLevel" defaultValue={editingChild?.educationLevel&&editingChild.educationLevel!=='NO_ESTUDIA'?editingChild.educationLevel:''} required><option value="">SELECCIONE</option>{EDUCATION_LEVELS.filter(([v])=>v!=='NO_ESTUDIA').map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div className="span-2"><label>Nombre de la institución *</label><input className="input uppercase" name="institutionName" defaultValue={editingChild?.institutionName||''} onInput={toUpperInput} required/></div></>}
      <label className="check-card"><input type="checkbox" checked={childDisease} onChange={e=>setChildDisease(e.target.checked)}/><span><strong>¿Padece alguna enfermedad?</strong><small>Si responde sí, describa la condición.</small></span></label>
      {childDisease&&<div className="span-2"><label>Descripción de la enfermedad *</label><textarea className="input textarea uppercase" name="diseaseDescription" defaultValue={editingChild?.diseaseDescription||''} onInput={toUpperInput} required/></div>}
    </div><div className="row-actions"><button className="btn"><Plus size={16}/> {editingChild?'Guardar cambios':'Registrar hijo'}</button>{editingChild&&<button type="button" className="btn secondary" onClick={()=>{setEditingChild(null);setChildStudying(false);setChildDisease(false)}}>Cancelar edición</button>}</div></form>
      <div className="card"><h3>Hijos registrados</h3>{row.children?.length===0?<p className="muted">No hay hijos registrados individualmente.</p>:<div className="cards-list">{row.children.map((c:any)=>{const a=childAge(c);return <div className="person-card" key={c.id}><div><div className="person-title"><strong>{[c.firstName,c.middleName,c.lastName,c.secondLastName].filter(Boolean).join(' ')}</strong><span className="status neutral">{a===null?'EDAD —':`${a} AÑOS`}</span></div><p>{c.identityNumber?`C.I. ${c.identityNumber}`:'SIN CÉDULA REGISTRADA'} · {a!==null&&a<=21?'≤ 21 AÑOS':'> 21 AÑOS'}</p><small>{c.studying?`${levelLabel(c.educationLevel)} · ${c.institutionName||'INSTITUCIÓN NO INDICADA'}`:'NO ESTUDIA'}</small><br/><small>Enfermedad: {c.hasDisease?(c.diseaseDescription||'SÍ'):'NO'}</small></div><div className="row-actions"><button className="btn secondary mini-btn" onClick={()=>editChild(c)}><Edit3 size={14}/> Editar</button><button className="btn secondary mini-btn" onClick={()=>confirm(`¿Eliminar el registro de ${c.firstName} ${c.lastName}?`)&&act(`/staff/${id}/children/${c.id}`,{method:'DELETE'},'Hijo eliminado')}><Trash2 size={14}/> Eliminar</button></div></div>})}</div>}</div>
    </div>

    <div className="section-title"><div><h2>Formación profesional</h2><p className="muted">Pregrado, especialización, maestría, doctorado y otros títulos.</p></div></div>
    <div className="details-grid"><form className="card form-section" onSubmit={qualification}><h3>{editingQ?'Editar título':'Agregar título profesional'}</h3><div className="form-grid"><div><label>Tipo *</label><select className="input" name="type" key={`t-${editingQ?.id||'new'}`} defaultValue={editingQ?.type||'PREGRADO'} required><option value="PREGRADO">PREGRADO</option><option value="ESPECIALIZACION">ESPECIALIZACIÓN</option><option value="MAESTRIA">MAESTRÍA</option><option value="DOCTORADO">DOCTORADO</option><option value="OTRO">OTRO</option></select></div><div><label>Año</label><input className="input" type="number" name="year" min="1900" max="2200" key={`y-${editingQ?.id||'new'}`} defaultValue={editingQ?.year||''}/></div><div className="span-2"><label>Título *</label><input className="input uppercase" name="title" onInput={toUpperInput} key={`q-${editingQ?.id||'new'}`} defaultValue={editingQ?.title||''} required/></div><div className="span-2"><label>Institución</label><input className="input uppercase" name="institution" onInput={toUpperInput} key={`i-${editingQ?.id||'new'}`} defaultValue={editingQ?.institution||''}/></div></div><div className="row-actions"><button className="btn"><Plus size={16}/> {editingQ?'Guardar título':'Agregar título'}</button>{editingQ&&<button type="button" className="btn secondary" onClick={()=>setEditingQ(null)}>Cancelar edición</button>}</div></form><div className="card"><h3>Títulos registrados</h3>{row.qualifications.length===0?<p className="muted">Sin títulos profesionales registrados.</p>:<div className="cards-list">{row.qualifications.map((q:any)=><div className="person-card" key={q.id}><div><div className="person-title"><GraduationCap size={17}/><strong>{qualLabel[q.type]||q.type}</strong></div><p>{q.title}</p><small>{q.institution||'Institución no indicada'}{q.year?` · ${q.year}`:''}</small></div><div className="row-actions"><button className="btn secondary mini-btn" onClick={()=>setEditingQ(q)}><Edit3 size={14}/> Editar</button><button className="btn secondary mini-btn" onClick={()=>confirm(`¿Eliminar el título ${q.title}?`)&&act(`/staff/${id}/qualifications/${q.id}`,{method:'DELETE'},'Título eliminado')}><Trash2 size={14}/> Eliminar</button></div></div>)}</div>}</div></div>

    <div className="section-title"><div><h2>Asignaciones docentes</h2><p className="muted">Un docente puede impartir varias materias en diferentes años y secciones.</p></div></div>
    {row.staffType!=='DOCENTE'?<div className="info-banner">Este registro está clasificado como {typeLabel(row.staffType)}. Las asignaciones académicas solo se habilitan para personal DOCENTE.</div>:<><form className="card form-section" onSubmit={assign}><div className="section-head"><div><h3>Asignar materia y sección</h3><p>Seleccione primero el año escolar, después la sección y finalmente una materia compatible con el plan y grado.</p></div><BookOpenCheck/></div><div className="form-grid cols-3"><div><label>Año escolar *</label><select className="input" value={yearId} onChange={e=>{setYearId(e.target.value);setSectionId('')}} required><option value="">SELECCIONE</option>{years.map(y=><option key={y.id} value={y.id}>{y.name}{y.active?' · ACTIVO':''}</option>)}</select></div><div><label>Sección *</label><select className="input" value={sectionId} onChange={e=>setSectionId(e.target.value)} required><option value="">SELECCIONE</option>{sections.map(s=><option key={s.id} value={s.id}>{s.gradeLevel}° · {s.name} · {s.studyPlan.code}{s.mentionName?` · ${s.mentionName}`:''}</option>)}</select></div><div><label>Materia *</label><select className="input" value={subjectId} onChange={e=>setSubjectId(e.target.value)} disabled={!sectionId} required><option value="">SELECCIONE</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.subject.name}</option>)}</select></div></div><button className="btn"><Link2 size={16}/> Registrar asignación</button></form><div className="table-wrap"><table><thead><tr><th>Año escolar</th><th>Grado / sección</th><th>Plan</th><th>Materia</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{row.assignments.length===0?<tr><td colSpan={6}>No tiene asignaciones docentes registradas.</td></tr>:row.assignments.map((a:any)=><tr key={a.id}><td>{a.section.academicYear.name}</td><td>{a.section.gradeLevel}° · {a.section.name}</td><td>{a.section.studyPlan.code}{a.section.mentionName?` · ${a.section.mentionName}`:''}</td><td>{a.studyPlanSubject.subject.name}</td><td><span className={`status ${a.active?'ok':'neutral'}`}>{a.active?'ACTIVA':'INACTIVA'}</span></td><td><button className="btn secondary mini-btn" onClick={()=>act(`/staff/${id}/assignments/${a.id}/active`,{method:'PATCH',body:JSON.stringify({active:!a.active})},a.active?'Asignación inactivada':'Asignación reactivada')}>{a.active?'Inactivar':'Reactivar'}</button></td></tr>)}</tbody></table></div></>}
  </Shell>
}
