'use client';
import {FormEvent,useEffect,useState} from 'react';
import Link from 'next/link';
import {useParams} from 'next/navigation';
import {ArrowLeft,BookOpenCheck,GraduationCap,LogOut,UserRound} from 'lucide-react';
import Shell from '@/components/Shell';
import {api} from '@/lib/api';
import {toUpperInput} from '@/lib/formRules';

function pretty(v?:string){return v?v.replaceAll('_',' '):'—'}
function idLabel(x:any){return x?.identityNumber?`${x.nationality==='VENEZOLANO'?'V':'E'}-${x.identityNumber}`:'SIN CÉDULA'}
function origin(v:string){return v==='PLAN_ACTUAL'?'PLAN ACTUAL':v==='MATERIA_PENDIENTE'?'PENDIENTE':'REPITENCIA'}
export default function EnrollmentDetail(){
  const {id}=useParams<{id:string}>();const [e,setE]=useState<any>(null),[msg,setMsg]=useState(''),[err,setErr]=useState('');
  async function load(){try{setE(await api(`/enrollments/${id}`));setErr('')}catch(x:any){setErr(x.message)}}useEffect(()=>{load()},[id]);
  async function withdraw(ev:FormEvent<HTMLFormElement>){ev.preventDefault();const f=new FormData(ev.currentTarget);try{await api(`/enrollments/${id}/withdraw`,{method:'POST',body:JSON.stringify({withdrawalDate:f.get('withdrawalDate'),reason:f.get('reason'),destinationInstitution:f.get('destinationInstitution')})});setMsg('Retiro registrado sin alterar el número de lista');await load()}catch(x:any){setErr(x.message)}}
  async function graduate(){try{await api(`/enrollments/${id}/graduate`,{method:'POST'});setMsg('Estudiante marcado como GRADUADO');await load()}catch(x:any){setErr(x.message)}}
  if(!e)return <Shell title="Matrícula">{err?<div className="alert">{err}</div>:<div className="card">Cargando…</div>}</Shell>;
  const primary=e.student.representatives?.find((x:any)=>x.isPrimary)||e.student.representatives?.[0];
  return <Shell title={`Matrícula ${e.academicYear.name}`}><div className="page-heading"><div><span className="eyebrow">Expediente anual</span><h1>{e.student.firstName} {e.student.lastName}</h1><p>{idLabel(e.student)} · {e.gradeLevel}° {e.section.name} · {e.section.mentionName?`Mención ${e.section.mentionName} · `:''}Plan {e.studyPlan.code}</p></div><div className="row-actions"><Link className="btn secondary" href="/enrollments"><ArrowLeft size={17}/> Volver</Link><Link className="btn secondary" href={`/students/${e.student.id}`}><UserRound size={17}/> Ficha estudiante</Link></div></div>{msg&&<div className="success-banner">{msg}</div>}{err&&<div className="alert">{err}</div>}
    <div className="grid metrics-4 compact-grid"><div className="card metric-card"><div><span className="muted">Condición</span><strong className="metric-text">{pretty(e.condition)}</strong></div></div><div className="card metric-card"><div><span className="muted">N° de lista</span><strong>{e.listNumber||'—'}</strong></div></div><div className="card metric-card"><div><span className="muted">Materias activas</span><strong>{e.curriculumSubjects.length}</strong></div></div><div className="card metric-card"><div><span className="muted">Inscripción</span><strong className="metric-text">{new Date(e.registrationDate).toLocaleDateString('es-VE')}</strong></div></div></div>
    <div className="details-grid"><section className="card"><h3>Datos académicos</h3><dl className="details-list"><div><dt>Año escolar</dt><dd>{e.academicYear.name}</dd></div><div><dt>Plan</dt><dd>{e.studyPlan.code} · {e.studyPlan.name}</dd></div><div><dt>Grado</dt><dd>{e.gradeLevel}° AÑO</dd></div><div><dt>Mención</dt><dd>{e.section.mentionName||'SIN DEFINIR'}</dd></div><div><dt>Sección</dt><dd>{e.section.name}</dd></div><div><dt>Matrícula tardía</dt><dd>{e.isLateEnrollment?'SÍ':'NO'}</dd></div><div><dt>Definitiva cerrada</dt><dd>{e.academicOutcomeFinalizedAt?new Date(e.academicOutcomeFinalizedAt).toLocaleDateString('es-VE'):'PENDIENTE'}</dd></div><div><dt>Condición académica definitiva</dt><dd>{pretty(e.academicCondition)}</dd></div>{e.previousEnrollment&&<div className="wide"><dt>Procede de</dt><dd>{e.previousEnrollment.academicYear.name} · {e.previousEnrollment.gradeLevel}° {e.previousEnrollment.section.name}{e.previousEnrollment.section.mentionName?` · ${e.previousEnrollment.section.mentionName}`:''} · {pretty(e.previousEnrollment.condition)}</dd></div>}</dl></section><section className="card"><h3>Representante principal</h3>{primary?<dl className="details-list"><div className="wide"><dt>Nombre</dt><dd><Link className="table-link" href={`/representatives/${primary.representativeId}`}>{primary.representative.firstName} {primary.representative.lastName}</Link></dd></div><div><dt>Parentesco</dt><dd>{pretty(primary.relationship)}</dd></div><div><dt>Teléfono</dt><dd>{primary.representative.phone1}</dd></div></dl>:<p className="warning-text">Sin representante vinculado.</p>}</section></div>
    <div className="section-title"><div><h2>Materias a cursar</h2><p className="muted">La lista se conserva por matrícula. En condición REPITIENTE contiene únicamente las materias reprobadas.</p></div></div><div className="curriculum-grid">{e.curriculumSubjects.map((x:any)=><div className={`curriculum-card origin-${x.origin.toLowerCase()}`} key={x.id}><BookOpenCheck size={18}/><div><strong>{x.studyPlanSubject.subject.name}</strong><span>{origin(x.origin)} · {x.studyPlanSubject.gradeLevel}°</span></div></div>)}</div>
    {e.pendingSubjects?.length>0&&<><div className="section-title"><div><h2>Materias pendientes</h2><p className="muted">Se generaron las cuatro oportunidades: octubre, diciembre, febrero y marzo.</p></div></div><div className="table-wrap"><table><thead><tr><th>Materia</th><th>Año origen</th><th>Estado</th><th>Oportunidades</th></tr></thead><tbody>{e.pendingSubjects.map((p:any)=><tr key={p.id}><td>{p.studyPlanSubject.subject.name}</td><td>{p.sourceAcademicYear}</td><td>{pretty(p.status)}</td><td>{p.opportunities.map((o:any)=>o.label).join(' · ')}</td></tr>)}</tbody></table></div></>}
    {e.withdrawal?<div className="warning-banner withdrawal-banner"><div><strong>Matrícula retirada</strong><span>{new Date(e.withdrawal.withdrawalDate).toLocaleDateString('es-VE')} · {e.withdrawal.reason}{e.withdrawal.destinationInstitution?` · Destino: ${e.withdrawal.destinationInstitution}`:''}</span></div><span className="status neutral">{pretty(e.condition)}</span></div>:<div className="details-grid enrollment-actions-grid"><form className="card form-section" onSubmit={withdraw}><div className="section-head"><div><h3>Registrar retiro</h3><p>El estudiante conserva su número de lista y cambia de condición.</p></div><LogOut size={20}/></div><div className="form-grid"><div><label>Fecha *</label><input className="input" name="withdrawalDate" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></div><div><label>Plantel de destino *</label><input className="input uppercase" name="destinationInstitution" onInput={toUpperInput} required/></div><div className="span-2"><label>Motivo *</label><textarea className="input textarea uppercase" name="reason" onInput={toUpperInput} required/></div></div><button className="btn secondary">Registrar retiro</button></form>{e.gradeLevel===e.studyPlan.maxGrade&&<section className="card form-section"><div className="section-head"><div><h3>Graduación</h3><p>Solo se habilita si la definitiva del último grado está completa y todas las materias están aprobadas.</p></div><GraduationCap size={20}/></div><button className="btn" onClick={graduate}><GraduationCap size={17}/> Validar y marcar graduado</button></section>}</div>}
  </Shell>
}
