'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { Activity, BookOpen, ClipboardCheck, ContactRound, Edit3, HeartPulse, Link2, Ruler, UserRoundPlus, UsersRound } from 'lucide-react';
import Shell from '@/components/Shell';
import { api } from '@/lib/api';
import { DIGITS_PATTERN, NAME_PATTERN, digitsOnlyInput, nameOnlyInput, toUpperInput } from '@/lib/formRules';

const DOCS=[
  ['CEDULA','Cédula de identidad'],['PARTIDA_NACIMIENTO','Partida de nacimiento'],['BOLETA_PROMOCION','Boleta de promoción'],['FOTO_ALUMNO','Foto del alumno'],['FOTO_REPRESENTANTE','Foto del representante'],['CEDULA_REPRESENTANTE','Copia de cédula del representante'],['NOTAS_CERTIFICADAS','Notas certificadas'],['CARTA_BUENA_CONDUCTA','Carta de buena conducta'],['CUENTA_BANCARIA','Copia de cuenta bancaria'],['INFORME_MEDICO','Informe médico'],['AUTORIZACION_REPRESENTANTE','Autorización de representante'],['OTRO','Otro documento'],
] as const;
const GARMENTS=['','10','11','12','13','14','15','16','S','M','L','XL','2XL','3XL'];

function age(date:string){const b=new Date(date),n=new Date();let a=n.getFullYear()-b.getFullYear();const m=n.getMonth()-b.getMonth();if(m<0||(m===0&&n.getDate()<b.getDate()))a--;return a}
function pretty(value?:string){return value?value.replaceAll('_',' ').toLowerCase().replace(/(^|\s)\S/g,x=>x.toUpperCase()):'—'}
function identityLabel(person:any){return person?.identityNumber?`${person.nationality==='VENEZOLANO'?'V':'E'}-${person.identityNumber}`:(person?.schoolIdentityNumber||'SIN IDENTIFICACIÓN')}
const TAB_KEYS=new Set(['resumen','representantes','antropometria','emergencia','documentos','trayectoria']);

export default function StudentDetail(){
  const {id}=useParams<{id:string}>();
  const [s,setS]=useState<any>(); const [representatives,setRepresentatives]=useState<any[]>([]); const [tab,setTab]=useState('resumen'); const [message,setMessage]=useState(''); const [error,setError]=useState('');
  async function load(){try{const [student,reps]=await Promise.all([api(`/students/${id}`),api('/representatives?active=true')]);setS(student);setRepresentatives(reps)}catch(e:any){setError(e.message)}}
  useEffect(()=>{load()},[id]);
  useEffect(()=>{const requested=new URLSearchParams(window.location.search).get('tab');if(requested&&TAB_KEYS.has(requested))setTab(requested)},[]);
  const primary=useMemo(()=>s?.representatives?.find((x:any)=>x.isPrimary),[s]);
  function ok(text:string){setMessage(text);setError('');setTimeout(()=>setMessage(''),2500)}
  async function call(path:string,options:RequestInit,text:string){try{await api(path,options);await load();ok(text)}catch(e:any){setError(e.message)}}
  if(error&&!s)return <Shell title="Estudiante"><div className="alert">{error}</div></Shell>;
  if(!s)return <Shell title="Estudiante"><div className="card">Cargando ficha integral…</div></Shell>;

  async function addAnthro(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const heightCm=Number(f.get('meters'))*100+Number(f.get('centimeters'));const weightGrams=Number(f.get('kg'))*1000+Number(f.get('grams'));const payload:any={heightCm,weightGrams,shoeSize:f.get('shoeSize')?Number(f.get('shoeSize')):undefined,shirtSize:f.get('shirtSize')||undefined,pantSize:f.get('pantSize')||undefined,measuredAt:f.get('measuredAt')||undefined};await call(`/students/${id}/anthropometrics`,{method:'POST',body:JSON.stringify(payload)},'Registro antropométrico guardado');e.currentTarget.reset()}
  async function addEmergency(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const upper=new Set(['firstName','middleName','lastName','secondLastName','address','notes']);const data:any={};for(const [k,v] of f.entries()){const raw=String(v).trim();if(raw)data[k]=upper.has(k)?raw.toLocaleUpperCase('es-VE'):raw}await call(`/students/${id}/emergency-contacts`,{method:'POST',body:JSON.stringify(data)},'Contacto de emergencia agregado');e.currentTarget.reset()}
  async function linkRepresentative(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const repId=String(f.get('representativeId'));if(!repId)return;const auth=String(f.get('authorizationDescription')||'').trim();const data={studentId:id,relationship:f.get('relationship'),isPrimary:f.get('isPrimary')==='on',livesWithStudent:f.get('livesWithStudent')==='on',authorizationDescription:auth?auth.toLocaleUpperCase('es-VE'):undefined};await call(`/representatives/${repId}/students`,{method:'POST',body:JSON.stringify(data)},'Representante vinculado')}
  async function unlinkRepresentative(repId:string,repName:string){if(!confirm(`¿Desvincular a ${repName} de este estudiante? Esta acción elimina solo la relación; no elimina ninguno de los dos registros.`))return;await call(`/representatives/${repId}/students/${id}/remove`,{method:'POST'},'Representante desvinculado')}
  async function setDocument(type:string,presented:boolean,notes?:string){await call(`/students/${id}/documents`,{method:'POST',body:JSON.stringify({type,presented,notes:notes||undefined})},'Expediente actualizado')}

  const tabs=[['resumen','Resumen',ContactRound],['representantes','Representantes',UsersRound],['antropometria','Antropometría',Ruler],['emergencia','Emergencia',HeartPulse],['documentos','Documentos',ClipboardCheck],['trayectoria','Trayectoria',BookOpen]] as const;
  return <Shell title={`${s.firstName} ${s.lastName}`}>
    <div className="profile-head card">
      <div className="avatar-lg">{s.firstName?.[0]}{s.lastName?.[0]}</div>
      <div className="profile-main"><div className="profile-title"><h1>{[s.firstName,s.middleName,s.lastName,s.secondLastName].filter(Boolean).join(' ')}</h1><span className={`status ${s.active?'ok':'neutral'}`}>{s.active?'Activo':'Inactivo'}</span></div><p>{identityLabel(s)} · {age(s.birthDate)} AÑOS · {s.sex}</p><div className="profile-meta"><span>{s.phone||'Sin teléfono'}</span><span>{s.email||'Sin correo'}</span><span>Representante: {primary?`${primary.representative.firstName} ${primary.representative.lastName}`:'NO ASIGNADO'}</span></div></div>
      <div className="profile-actions"><Link className="btn secondary" href={`/students/${id}/edit`}><Edit3 size={16}/> Editar</Link><button className="btn secondary" onClick={()=>call(`/students/${id}/active`,{method:'PATCH',body:JSON.stringify({active:!s.active})},s.active?'Estudiante marcado como inactivo':'Estudiante reactivado')}>{s.active?'Inactivar':'Reactivar'}</button></div>
    </div>
    {message&&<div className="success-banner">{message}</div>}{error&&<div className="alert">{error}</div>}
    <div className="tabs">{tabs.map(([key,label,Icon])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}><Icon size={16}/>{label}</button>)}</div>

    {tab==='resumen'&&<div className="stack">
      {s.representatives.length===0&&<div className="warning-banner rep-warning"><div><strong>ESTE ESTUDIANTE NO TIENE REPRESENTANTE ASIGNADO</strong><span>Vincula un representante existente o crea uno nuevo; un mismo representante puede estar relacionado con varios estudiantes.</span></div><div className="row-actions"><Link className="btn secondary" href={`/students/${id}/representatives/link`}><Link2 size={16}/> Asignar existente</Link><Link className="btn" href={`/representatives/new?studentId=${id}`}><UserRoundPlus size={16}/> Crear representante</Link></div></div>}
      <div className="grid metrics-4 compact-grid">
        <div className="card metric-card"><ContactRound size={20}/><div><span className="muted">Identificación</span><strong>{identityLabel(s)}</strong></div></div>
        <div className="card metric-card"><Activity size={20}/><div><span className="muted">Grupo sanguíneo</span><strong>{s.bloodType||'—'}</strong></div></div>
        <div className="card metric-card"><UsersRound size={20}/><div><span className="muted">Representantes</span><strong>{s.representatives.length}</strong></div></div>
        <div className="card metric-card"><ClipboardCheck size={20}/><div><span className="muted">Documentos</span><strong>{s.documents.filter((d:any)=>d.presented).length}/{DOCS.length}</strong></div></div>
      </div>
      <div className="details-grid">
        <section className="card"><h3>Datos personales</h3><dl className="details-list"><div><dt>Nacionalidad</dt><dd>{pretty(s.nationality)}</dd></div><div><dt>Estado civil</dt><dd>{pretty(s.maritalStatus)}</dd></div><div><dt>Nacimiento</dt><dd>{new Date(s.birthDate).toLocaleDateString('es-VE')} · {s.birthPlace}</dd></div><div><dt>Entidad de nacimiento</dt><dd>{[s.birthState?.name,s.birthMunicipality?.name,s.birthParish?.name].filter(Boolean).join(' · ')||'—'}</dd></div><div><dt>Dirección</dt><dd>{s.address}</dd></div><div><dt>Residencia</dt><dd>{[s.residenceState?.name,s.residenceMunicipality?.name,s.residenceParish?.name].filter(Boolean).join(' · ')||'—'}</dd></div></dl></section>
        <section className="card"><h3>Familia y salud</h3><dl className="details-list"><div><dt>Madre</dt><dd>{s.motherName||'—'} {s.motherIdentity&&`· ${s.motherIdentity}`}</dd></div><div><dt>Padre</dt><dd>{s.fatherName||'—'} {s.fatherIdentity&&`· ${s.fatherIdentity}`}</dd></div><div><dt>Convive con</dt><dd>{pretty(s.livingWith)}</dd></div><div><dt>Discapacidad</dt><dd>{s.disability?`Sí${s.disabilityDetails?` · ${s.disabilityDetails}`:''}`:'No'}</dd></div><div><dt>Informe médico</dt><dd>{s.medicalReport?'Sí':'No'}</dd></div><div><dt>Alergias</dt><dd>{s.allergy?`Sí${s.allergyDetails?` · ${s.allergyDetails}`:''}`:'No'}</dd></div></dl></section>
      </div>
      {(s.originSchool||s.destinationSchool||s.observations)&&<section className="card"><h3>Procedencia y observaciones</h3><dl className="details-list"><div><dt>Plantel de procedencia</dt><dd>{s.originSchool||'—'}</dd></div><div><dt>Plantel de destino</dt><dd>{s.destinationSchool||'—'}</dd></div><div className="wide"><dt>Observaciones</dt><dd>{s.observations||'—'}</dd></div></dl></section>}
    </div>}

    {tab==='representantes'&&<div className="stack">
      <div className="section-title"><div><h2>Representantes vinculados</h2><p className="muted">Un representante puede estar asociado con varios estudiantes.</p></div><div className="row-actions"><Link className="btn secondary" href={`/students/${id}/representatives/link`}><Link2 size={17}/> Vincular existente</Link><Link className="btn" href={`/representatives/new?studentId=${id}`}><UserRoundPlus size={17}/> Crear representante</Link></div></div>
      <div className="cards-list">{s.representatives.length===0?<div className="card empty-state">No hay representantes vinculados.</div>:s.representatives.map((x:any)=>{const repName=`${x.representative.firstName} ${x.representative.lastName}`;return <div className="card person-card" key={x.representativeId}><div><div className="person-title"><Link href={`/representatives/${x.representativeId}`}>{repName}</Link>{x.isPrimary&&<span className="status ok">Principal</span>}</div><p>{identityLabel(x.representative)} · {pretty(x.relationship)} · {x.representative.phone1}</p><small>{x.livesWithStudent?'Vive con el estudiante':'No vive con el estudiante'}{x.authorizationDescription?` · ${x.authorizationDescription}`:''}</small></div><div className="row-actions"><Link className="btn secondary" href={`/students/${id}/representatives/${x.representativeId}/edit`}><Edit3 size={15}/> Modificar vínculo</Link><button className="btn secondary" onClick={()=>unlinkRepresentative(x.representativeId,repName)}>Desvincular</button></div></div>})}</div>
      <form className="card form-section" onSubmit={linkRepresentative}><div className="section-head"><div><h3>Vincular representante existente</h3><p>Selecciona una persona ya registrada.</p></div></div><div className="form-grid cols-3"><div><label>Representante</label><select className="input" name="representativeId" required><option value="">Seleccione</option>{representatives.filter(r=>!s.representatives.some((x:any)=>x.representativeId===r.id)).map(r=><option key={r.id} value={r.id}>{identityLabel(r)} · {r.firstName} {r.lastName}</option>)}</select></div><div><label>Parentesco</label><select className="input" name="relationship"><option>MADRE</option><option>PADRE</option><option>AUTORIZADO</option><option>OTRO</option></select></div><div><label>Descripción de autorización</label><input className="input uppercase" name="authorizationDescription" onInput={toUpperInput}/></div><label className="check-card"><input type="checkbox" name="isPrimary" defaultChecked={s.representatives.length===0}/><span><strong>Representante principal</strong><small>Será el contacto principal.</small></span></label><label className="check-card"><input type="checkbox" name="livesWithStudent"/><span><strong>Vive con el estudiante</strong><small>Dato requerido para la ficha.</small></span></label></div><button className="btn">Vincular representante</button></form>
    </div>}

    {tab==='antropometria'&&<div className="stack">
      <form className="card form-section" onSubmit={addAnthro}><div className="section-head"><div><h2>Nuevo registro antropométrico</h2><p>Se conserva el histórico de cada medición.</p></div></div><div className="form-grid cols-3"><div><label>Fecha</label><input className="input" type="date" name="measuredAt" defaultValue={new Date().toISOString().slice(0,10)}/></div><div className="inline-fields"><div><label>Estatura · metros</label><input className="input" type="number" name="meters" min="0" max="2" defaultValue="1" required/></div><div><label>centímetros</label><input className="input" type="number" name="centimeters" min="0" max="99" defaultValue="50" required/></div></div><div className="inline-fields"><div><label>Peso · kg</label><input className="input" type="number" name="kg" min="10" max="300" required/></div><div><label>gramos</label><input className="input" type="number" name="grams" min="0" max="999" defaultValue="0" required/></div></div><div><label>Talla camisa</label><select className="input" name="shirtSize">{GARMENTS.map(x=><option key={x||'none'} value={x}>{x||'Seleccione'}</option>)}</select></div><div><label>Talla pantalón</label><select className="input" name="pantSize">{GARMENTS.map(x=><option key={x||'none'} value={x}>{x||'Seleccione'}</option>)}</select></div><div><label>Talla zapatos (20–46)</label><input className="input" type="number" min="20" max="46" name="shoeSize"/></div></div><button className="btn">Guardar medición</button></form>
      <div className="table-wrap"><table><thead><tr><th>Fecha</th><th>Estatura</th><th>Peso</th><th>Camisa</th><th>Pantalón</th><th>Zapato</th></tr></thead><tbody>{s.anthropometrics.length===0?<tr><td colSpan={6}>Sin mediciones registradas.</td></tr>:s.anthropometrics.map((a:any)=><tr key={a.id}><td>{new Date(a.measuredAt).toLocaleDateString('es-VE')}</td><td>{Math.floor(a.heightCm/100)} m {a.heightCm%100} cm</td><td>{Math.floor(a.weightGrams/1000)} kg {a.weightGrams%1000} g</td><td>{a.shirtSize||'—'}</td><td>{a.pantSize||'—'}</td><td>{a.shoeSize||'—'}</td></tr>)}</tbody></table></div>
    </div>}

    {tab==='emergencia'&&<div className="stack">
      <form className="card form-section" onSubmit={addEmergency}><div className="section-head"><div><h2>Referencia de emergencia</h2><p>Persona distinta del representante para situaciones en las que no pueda ser contactado.</p></div></div><div className="form-grid cols-3"><div><label>Primer nombre *</label><input className="input uppercase" name="firstName" pattern={NAME_PATTERN} title="Solo letras" onInput={nameOnlyInput} required/></div><div><label>Segundo nombre</label><input className="input uppercase" name="middleName" pattern={NAME_PATTERN} title="Solo letras" onInput={nameOnlyInput}/></div><div><label>Primer apellido *</label><input className="input uppercase" name="lastName" pattern={NAME_PATTERN} title="Solo letras" onInput={nameOnlyInput} required/></div><div><label>Segundo apellido</label><input className="input uppercase" name="secondLastName" pattern={NAME_PATTERN} title="Solo letras" onInput={nameOnlyInput}/></div><div><label>Cédula</label><input className="input" name="identityNumber" inputMode="numeric" pattern={DIGITS_PATTERN} title="Solo números" onInput={digitsOnlyInput}/></div><div><label>Teléfono *</label><input className="input" name="phone" inputMode="numeric" pattern="[0-9]{10,15}" title="Entre 10 y 15 dígitos" onInput={digitsOnlyInput} required/></div><div className="span-3"><label>Dirección</label><input className="input uppercase" name="address" onInput={toUpperInput}/></div><div className="span-3"><label>Observaciones</label><textarea className="input textarea uppercase" name="notes" onInput={toUpperInput}/></div></div><button className="btn">Agregar contacto</button></form>
      <div className="cards-list">{s.emergencyContacts.length===0?<div className="card empty-state">No hay contactos de emergencia.</div>:s.emergencyContacts.map((c:any)=><div className="card person-card" key={c.id}><div><div className="person-title"><strong>{[c.firstName,c.middleName,c.lastName,c.secondLastName].filter(Boolean).join(' ')}</strong></div><p>{c.identityNumber||'Sin cédula'} · {c.phone}</p><small>{c.address||'Sin dirección'}{c.notes?` · ${c.notes}`:''}</small></div><button className="btn secondary" onClick={()=>call(`/students/${id}/emergency-contacts/${c.id}/remove`,{method:'POST'},'Contacto eliminado')}>Eliminar</button></div>)}</div>
    </div>}

    {tab==='documentos'&&<div className="stack"><div className="section-title"><div><h2>Expediente documental</h2><p className="muted">Control de recaudos consignados por el estudiante.</p></div></div><div className="document-grid">{DOCS.map(([type,label])=>{const doc=s.documents.find((d:any)=>d.type===type);return <div className={`card document-card ${doc?.presented?'done':''}`} key={type}><div className="document-main"><strong>{label}</strong><p>{doc?.presented?'Consignado':'Pendiente'}</p><input className="input doc-note uppercase" placeholder="Observación del recaudo" onInput={toUpperInput} defaultValue={doc?.notes||''} onBlur={e=>{if(e.target.value!==(doc?.notes||''))setDocument(type,!!doc?.presented,e.target.value)}}/></div><label className="switch-line"><input type="checkbox" checked={!!doc?.presented} onChange={e=>setDocument(type,e.target.checked,doc?.notes)}/><span>{doc?.presented?'Sí':'No'}</span></label></div>})}</div></div>}

    {tab==='trayectoria'&&<div className="stack"><div className="section-title"><div><h2>Trayectoria de matrícula</h2><p className="muted">Histórico por año escolar, plan, grado, sección y condición.</p></div><Link className="btn" href="/enrollments">Ir a matrícula</Link></div><div className="table-wrap"><table><thead><tr><th>Año</th><th>Plan</th><th>Grado</th><th>Sección</th><th>N° lista</th><th>Condición</th><th>Inscripción</th></tr></thead><tbody>{s.enrollments.length===0?<tr><td colSpan={7}>El estudiante todavía no posee matrícula.</td></tr>:s.enrollments.map((e:any)=><tr key={e.id}><td>{e.academicYear.name}</td><td>{e.studyPlan.code}</td><td>{e.gradeLevel}°</td><td>{e.section.name}</td><td>{e.listNumber||'—'}</td><td><span className="status neutral">{pretty(e.condition)}</span></td><td>{new Date(e.registrationDate).toLocaleDateString('es-VE')}</td></tr>)}</tbody></table></div></div>}
  </Shell>
}
