'use client';
import {FormEvent,useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {ArrowLeft,Search,UserPlus} from 'lucide-react';
import Shell from '@/components/Shell';
import {api} from '@/lib/api';
import {digitsOnlyInput} from '@/lib/formRules';

const GARMENTS=['','10','11','12','13','14','15','16','S','M','L','XL','2XL','3XL'];
function idLabel(x:any){return x?.identityNumber?`${x.nationality==='VENEZOLANO'?'V':'E'}-${x.identityNumber}`:'SIN CÉDULA'}
export default function NewEnrollment(){
  const router=useRouter();
  const [years,setYears]=useState<any[]>([]),[plans,setPlans]=useState<any[]>([]),[sections,setSections]=useState<any[]>([]),[nationality,setNationality]=useState('VENEZOLANO'),[identity,setIdentity]=useState(''),[student,setStudent]=useState<any>(null),[yearId,setYearId]=useState(''),[planId,setPlanId]=useState(''),[grade,setGrade]=useState(1),[sectionId,setSectionId]=useState(''),[err,setErr]=useState(''),[saving,setSaving]=useState(false);
  useEffect(()=>{Promise.all([api('/academic/years'),api('/academic/plans')]).then(([y,p]:any[])=>{setYears(y);setPlans(p);const a=y.find((x:any)=>x.active)||y[0];if(a)setYearId(a.id);if(p[0])setPlanId(p[0].id)}).catch((e:any)=>setErr(e.message))},[]);
  useEffect(()=>{if(!yearId||!planId)return;api(`/academic/sections?academicYearId=${yearId}&studyPlanId=${planId}&gradeLevel=${grade}`).then((s:any[])=>{setSections(s);setSectionId(s[0]?.id||'')}).catch((e:any)=>setErr(e.message))},[yearId,planId,grade]);
  async function search(e:FormEvent){e.preventDefault();setErr('');try{const rows:any[]=await api(`/students?search=${encodeURIComponent(identity)}&active=true`);const exact=rows.find(x=>x.identityNumber===identity&&x.nationality===nationality);if(!exact)throw new Error('No se encontró un estudiante activo con esa nacionalidad y cédula');setStudent(await api(`/students/${exact.id}`))}catch(e:any){setStudent(null);setErr(e.message)}}
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!student)return;const f=new FormData(e.currentTarget);setSaving(true);setErr('');try{const meters=Number(f.get('meters')||0),centimeters=Number(f.get('centimeters')||0),kg=Number(f.get('kg')||0),grams=Number(f.get('grams')||0);const body:any={studentId:student.id,academicYearId:yearId,studyPlanId:planId,sectionId,gradeLevel:grade,registrationDate:f.get('registrationDate'),lastApprovedYear:f.get('lastApprovedYear')||undefined,literal:f.get('literal')||undefined};if(meters||centimeters||kg||grams){body.heightCm=meters*100+centimeters;body.weightGrams=kg*1000+grams;body.shirtSize=f.get('shirtSize')||undefined;body.pantSize=f.get('pantSize')||undefined;body.shoeSize=f.get('shoeSize')?Number(f.get('shoeSize')):undefined}const created=await api('/enrollments',{method:'POST',body:JSON.stringify(body)});router.push(`/enrollments/${created.id}`)}catch(e:any){setErr(e.message)}finally{setSaving(false)}}
  const plan=plans.find(x=>x.id===planId),hasRep=student?.representatives?.some((x:any)=>x.representative?.active!==false);
  return <Shell title="Primera matrícula"><div className="page-heading"><div><span className="eyebrow">Ingreso al plantel</span><h1>Primera matrícula</h1><p>Para estudiantes que todavía no poseen una matrícula histórica en el sistema. Si ya cursaron en ETIMA, utilice Reinscripción.</p></div><Link className="btn secondary" href="/enrollments"><ArrowLeft size={17}/> Volver</Link></div>{err&&<div className="alert">{err}</div>}
    <form className="card form-section enrollment-lookup" onSubmit={search}><div className="section-head"><div><h2>1. Buscar estudiante registrado</h2><p>El estudiante debe existir previamente en la ficha integral.</p></div><span className="step-pill">1</span></div><div className="form-grid reenroll-search-grid"><div><label>Nacionalidad</label><select className="input" value={nationality} onChange={e=>setNationality(e.target.value)}><option value="VENEZOLANO">V</option><option value="EXTRANJERO">E</option></select></div><div className="span-2"><label>Cédula</label><input className="input" inputMode="numeric" value={identity} onChange={e=>setIdentity(e.target.value.replace(/\D/g,''))} onInput={digitsOnlyInput} required/></div><button className="btn lookup-btn"><Search size={17}/> Buscar</button></div></form>
    {student&&<form className="stack" onSubmit={submit}><section className="card form-section"><div className="section-head"><div><h2>2. Estudiante</h2><p>Verifique la identidad y el representante antes de continuar.</p></div><span className="step-pill">2</span></div><div className="student-reenroll-head"><div className="avatar-lg">{student.firstName[0]}{student.lastName[0]}</div><div><h3>{[student.firstName,student.middleName,student.lastName,student.secondLastName].filter(Boolean).join(' ')}</h3><p>{idLabel(student)} · {student.address}</p></div><Link className="btn secondary" href={`/students/${student.id}/edit`}>Actualizar ficha</Link></div>{!hasRep&&<div className="warning-banner"><div><strong>Falta representante</strong><span>No es posible formalizar matrícula sin al menos un representante activo vinculado.</span></div><div className="row-actions"><Link className="btn secondary" href={`/students/${student.id}/representatives/link`}>Asignar existente</Link><Link className="btn" href={`/representatives/new?studentId=${student.id}`}>Crear representante</Link></div></div>}</section>
      <section className="card form-section"><div className="section-head"><div><h2>3. Datos académicos de ingreso</h2><p>Seleccione el año, plan, grado y sección de la primera matrícula.</p></div><span className="step-pill">3</span></div><div className="form-grid cols-3"><div><label>Año escolar *</label><select className="input" value={yearId} onChange={e=>setYearId(e.target.value)} required>{years.map(y=><option key={y.id} value={y.id}>{y.name}{y.active?' · ACTIVO':''}</option>)}</select></div><div><label>Plan de estudio *</label><select className="input" value={planId} onChange={e=>{setPlanId(e.target.value);setGrade(1)}} required>{plans.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></div><div><label>Grado a cursar *</label><select className="input" value={grade} onChange={e=>setGrade(Number(e.target.value))}>{Array.from({length:plan?.maxGrade||1},(_,i)=>i+1).map(g=><option key={g} value={g}>{g}° AÑO</option>)}</select></div><div><label>Sección *</label><select className="input" value={sectionId} onChange={e=>setSectionId(e.target.value)} required><option value="">Seleccione</option>{sections.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div><label>Fecha inscripción *</label><input className="input" name="registrationDate" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></div><div><label>Último año aprobado</label><input className="input uppercase" name="lastApprovedYear"/></div><div><label>Literal</label><input className="input uppercase" name="literal"/></div></div>{sections.length===0&&<div className="warning-banner"><div><strong>No existen secciones para esta combinación.</strong><span>Configure primero una sección para el año, plan y grado.</span></div><Link className="btn secondary" href="/enrollments/configuration">Configurar</Link></div>}</section>
      <section className="card form-section"><div className="section-head"><div><h2>4. Antropometría de ingreso</h2><p>Esta medición queda ligada al año escolar.</p></div><span className="step-pill">4</span></div><div className="form-grid cols-3"><div className="inline-fields"><div><label>Metros</label><input className="input" type="number" name="meters" min="0" max="2" defaultValue="1" required/></div><div><label>Centímetros</label><input className="input" type="number" name="centimeters" min="0" max="99" defaultValue="50" required/></div></div><div className="inline-fields"><div><label>Kilos</label><input className="input" type="number" name="kg" min="10" max="300" required/></div><div><label>Gramos</label><input className="input" type="number" name="grams" min="0" max="999" defaultValue="0" required/></div></div><div><label>Zapatos</label><input className="input" type="number" name="shoeSize" min="20" max="46"/></div><div><label>Camisa</label><select className="input" name="shirtSize">{GARMENTS.map(x=><option key={x||'none'} value={x}>{x||'Seleccione'}</option>)}</select></div><div><label>Pantalón</label><select className="input" name="pantSize">{GARMENTS.map(x=><option key={x||'none'} value={x}>{x||'Seleccione'}</option>)}</select></div></div></section>
      <div className="action-bar"><Link className="btn secondary" href="/enrollments">Cancelar</Link><button className="btn" disabled={saving||!hasRep||!sectionId}><UserPlus size={17}/>{saving?'Guardando…':'Formalizar matrícula'}</button></div>
    </form>}
  </Shell>
}
